# Generated by Django 3.0.6 on 2020-07-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id_abono', models.FloatField(primary_key=True, serialize=False)),
                ('monto_abonado', models.BigIntegerField()),
                ('fecha_abono', models.DateField()),
            ],
            options={
                'db_table': 'abono',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_bol', models.FloatField(primary_key=True, serialize=False)),
                ('fiado', models.FloatField()),
                ('estado_pago', models.FloatField()),
                ('total_boleta', models.BigIntegerField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comu', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_det_ped', models.FloatField(primary_key=True, serialize=False)),
                ('cantidad_prod_p', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_det_ven', models.FloatField(primary_key=True, serialize=False)),
                ('cantidad_prod_v', models.BigIntegerField()),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Errores',
            fields=[
                ('id_error', models.FloatField(primary_key=True, serialize=False)),
                ('mensaje_error', models.CharField(max_length=500)),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'errores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id_est', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_estad_id_tipo', models.BigIntegerField(blank=True, null=True)),
                ('nombre_estadistica', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estadisticas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id_familia', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_familia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'familia_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KilosLitros',
            fields=[
                ('id_kg_lt', models.FloatField(primary_key=True, serialize=False)),
                ('descripcion_kg_lt', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'kilos_litros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id_nosotros', models.FloatField(primary_key=True, serialize=False)),
                ('titulo_pagina', models.CharField(max_length=50)),
                ('titulo_mision', models.CharField(max_length=50)),
                ('titulo_vision', models.CharField(max_length=50)),
                ('descripcion_mision', models.CharField(max_length=1000)),
                ('descripcion_vision', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'nosotros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio_compra', models.BigIntegerField()),
                ('precio_venta', models.BigIntegerField()),
                ('stock', models.BigIntegerField()),
                ('stock_critico', models.FloatField()),
                ('codigo_barra', models.BigIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=200)),
                ('direccion_proveedor', models.CharField(max_length=200)),
                ('telefono_proveedor', models.CharField(max_length=12)),
                ('correo_proveedor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvProd',
            fields=[
                ('id_prov_prod', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prov_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecepPedido',
            fields=[
                ('id_recep_p', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_recp', models.DateField()),
            ],
            options={
                'db_table': 'recep_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('id_tip_prod', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_prod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id_tipo_u', models.FloatField(primary_key=True, serialize=False)),
                ('nom_tipo_u', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_m', models.CharField(max_length=30)),
                ('apellido_p', models.CharField(max_length=30)),
                ('fecha_nac', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('rut', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_vent', models.FloatField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
